export const FLOW_STOPS = [
  {
    id: 'explore',
    x: 286,
    y: 36,
    title: '1. Explore Stays',
    sub: 'Search & filter real-time',
    icon: '🔍',
    caption: 'Explore verified stays matching your budget & location in real-time.',
  },
  {
    id: 'listing',
    x: 376,
    y: 126,
    title: '2. Stay Details',
    sub: 'Inspect rooms & amenities',
    icon: '🏢',
    caption: 'Check complete pricing, verified amenities, and transparent stay details.',
  },
  {
    id: 'visit',
    x: 466,
    y: 216,
    title: '3. Schedule Visit',
    sub: 'Zero brokerage booking',
    icon: '📅',
    caption: 'Schedule a physical visit directly with zero brokerage or middleman fees.',
  },
  {
    id: 'approval',
    x: 376,
    y: 306,
    title: '4. Owner Approval',
    sub: 'Direct instant verification',
    icon: '🤝',
    caption: 'Direct owner approval ensures instant confirmation and seamless scheduling.',
  },
  {
    id: 'checkin',
    x: 286,
    y: 396,
    title: '5. Confirmation',
    sub: 'Unlock food credits',
    icon: '🎁',
    caption: 'One scan checks you in instantly & unlocks rewards for nearby meals!',
  },
];
