import { useEffect, useRef } from 'react';
import { Icon } from '../components/common/atoms/Icon/Icon';
import { SecHead } from '../components/common/molecules/SecHead/SecHead';
import { REDUCED } from '../hooks/useSite';
import { AP_CITIES } from '../components/cities/utils/apCities';
import { CITY_CARDS } from '../components/cities/utils/cityCards';
import { Box, Break, Emphasis, Figure, Heading, Image, Inline, Region, Text } from '../components/common/atoms';


/* Skyline artwork generated by scripts/generate-art.mjs — nothing remote, so
   the grid can never break on someone else's CDN. */

/* The AP city rows stagger in once the section is reached, rather than all
   arriving at once — the same `vis` class the original used. */
function useApStagger(ref) {
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const cards = [...el.querySelectorAll('.apc')];
    if (REDUCED) { cards.forEach(c => c.classList.add('vis')); return; }

    const io = new IntersectionObserver(([e]) => {
      if (!e.isIntersecting) return;
      cards.forEach((c, i) => setTimeout(() => c.classList.add('vis'), i * 110));
      io.disconnect();
    }, { threshold: 0.15 });

    io.observe(el);
    return () => io.disconnect();
  }, [ref]);
}

export function Cities() {
  const ap = useRef(null);
  useApStagger(ap);

  return (
    <>
      <Region id="ap-section" ref={ap}>
        <Box className="ap-inner">
          <Box className="reveal">
            <Inline className="ap-tag">Our story</Inline>
            <Heading level={2} className="ap-h2">
              Started in Vizag.<Break /><Emphasis>Opening city by city.</Emphasis>
            </Heading>
            <Text className="ap-sub">
              We do not launch a city until a scout has walked its rooms and eaten
              at its kitchens. That is slower than switching on a map, and it is
              the reason a Lampose listing means something.
            </Text>
          </Box>

          <Box className="ap-cities">
            {AP_CITIES.map((c, i) => (
              <Box className="apc" key={c.name} style={{ '--i': String(i) }}>
                <Box className="apc-flag"><Icon name={c.icon} /></Box>
                <Box className="apc-info">
                  <Heading level={4}>{c.name}</Heading>
                  <Inline>{c.sub}</Inline>
                </Box>
                <Box className={`apc-badge ${c.hq ? 'badge-hq' : 'badge-soon'}`}>
                  {c.badge}
                </Box>
              </Box>
            ))}
          </Box>

          {/* The location map, filling the right column as on lampose.com.
              The pulse is anchored to the glow at the base of the pin in the
              artwork (52% / 53%), so it reads as the map locating itself. */}
          <Box className="ap-visual">
            <Figure className="ap-map">
              <Image
                src="/images/vizag-lampose.png"
                alt="Map of Visakhapatnam marking the Lampose location, with Gajuwaka, Madhurawada, Pendurthi, Gopalapatnam, Duvvada, Sheela Nagar, Rushikonda Beach, Yarada Beach and Visakhapatnam Port"
                width="1402" height="1122" loading="lazy" decoding="async"
              />
              <Inline className="ap-map__ping" aria-hidden="true" />
            </Figure>
          </Box>
        </Box>
      </Region>

      <Box className="divider" />

      <Region id="cities">
        <Box className="sec-inner">
          <SecHead
            tag="Where we are" title="Live in one city." em="Verified in six."
            sub="Vizag is open today. The rest are in verification — rooms walked, kitchens tasted, in that order."
          />

          <Box className="city-grid reveal">
            {CITY_CARDS.map((c, i) => (
              <Box className="ccard" key={c.name} style={{ '--i': String(i) }}>
                <Box className="cimg-wrap">
                  <Image
                    className="cimg" src={c.src} alt={c.name} loading="lazy"
                    onError={e => {
                      // Remote hosts go away; fall back to the brand ground
                      // rather than leaving a broken-image glyph in the grid.
                      e.currentTarget.style.display = 'none';
                      e.currentTarget.parentElement.style.background = 'var(--forest)';
                    }}
                  />
                  <Box className="cimg-overlay" />
                </Box>
                <Box className="ccard-body">
                  <Box className="cname">{c.name}</Box>
                  <Box className={`cstat ${c.live ? 'cs-live' : 'cs-soon'}`}>
                    {c.live ? 'Live now' : 'In verification'}
                  </Box>
                </Box>
              </Box>
            ))}
          </Box>
        </Box>
      </Region>
    </>
  );
}
