import { useEffect, useRef } from 'react';
import Icon from '../components/Icon';
import { SecHead } from '../components/Chrome';
import { REDUCED } from '../hooks/useSite';

const AP_CITIES = [
  { icon: 'wave',    name: 'Visakhapatnam', sub: 'Where we started, and still the biggest', badge: 'Live', hq: true },
  { icon: 'temple',  name: 'Vijayawada',    sub: 'Scouts walking the first properties now', badge: 'Soon' },
  { icon: 'pillars', name: 'Amaravati',     sub: 'Capital region — opening with Vijayawada', badge: 'Soon' },
  { icon: 'leaf',    name: 'Guntur',        sub: 'Kitchens signed, rooms in verification', badge: 'Soon' },
  { icon: 'hill',    name: 'Tirupati',      sub: 'Built around the student corridor', badge: 'Soon' },
  { icon: 'boat',    name: 'Kakinada',      sub: 'Next after the Guntur rollout', badge: 'Soon' },
];

/* Skyline artwork generated by scripts/generate-art.mjs — nothing remote, so
   the grid can never break on someone else's CDN. */
const CITY_CARDS = [
  { name: 'Visakhapatnam', live: true, src: '/images/city-visakhapatnam.svg' },
  { name: 'Hyderabad', src: '/images/city-hyderabad.svg' },
  { name: 'Vijayawada', src: '/images/city-vijayawada.svg' },
  { name: 'Amaravati', src: '/images/city-amaravati.svg' },
  { name: 'Guntur', src: '/images/city-guntur.svg' },
  { name: 'Tirupati', src: '/images/city-tirupati.svg' },
  { name: 'Kakinada', src: '/images/city-kakinada.svg' },
  { name: 'Nellore', src: '/images/city-nellore.svg' },
  { name: 'Kurnool', src: '/images/city-kurnool.svg' },
];

/* The AP city rows stagger in once the section is reached, rather than all
   arriving at once — the same `vis` class the original used. */
function useApStagger(ref) {
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const cards = [...el.querySelectorAll('.apc')];
    if (REDUCED) { cards.forEach(c => c.classList.add('vis')); return; }

    const io = new IntersectionObserver(([e]) => {
      if (!e.isIntersecting) return;
      cards.forEach((c, i) => setTimeout(() => c.classList.add('vis'), i * 110));
      io.disconnect();
    }, { threshold: 0.15 });

    io.observe(el);
    return () => io.disconnect();
  }, [ref]);
}

export default function Cities() {
  const ap = useRef(null);
  useApStagger(ap);

  return (
    <>
      <section id="ap-section" ref={ap}>
        <div className="ap-inner">
          <div className="reveal">
            <span className="ap-tag">Our story</span>
            <h2 className="ap-h2">
              Started in Vizag.<br /><em>Opening city by city.</em>
            </h2>
            <p className="ap-sub">
              We do not launch a city until a scout has walked its rooms and eaten
              at its kitchens. That is slower than switching on a map, and it is
              the reason a Lampose listing means something.
            </p>
          </div>

          <div className="ap-cities">
            {AP_CITIES.map((c, i) => (
              <div className="apc" key={c.name} style={{ '--i': String(i) }}>
                <div className="apc-flag"><Icon name={c.icon} /></div>
                <div className="apc-info">
                  <h4>{c.name}</h4>
                  <span>{c.sub}</span>
                </div>
                <div className={`apc-badge ${c.hq ? 'badge-hq' : 'badge-soon'}`}>
                  {c.badge}
                </div>
              </div>
            ))}
          </div>

          {/* The location map, filling the right column as on lampose.com.
              The pulse is anchored to the glow at the base of the pin in the
              artwork (52% / 53%), so it reads as the map locating itself. */}
          <div className="ap-visual">
            <figure className="ap-map">
              <img
                src="/images/vizag-lampose.png"
                alt="Map of Visakhapatnam marking the Lampose location, with Gajuwaka, Madhurawada, Pendurthi, Gopalapatnam, Duvvada, Sheela Nagar, Rushikonda Beach, Yarada Beach and Visakhapatnam Port"
                width="1402" height="1122" loading="lazy" decoding="async"
              />
              <span className="ap-map__ping" aria-hidden="true" />
            </figure>
          </div>
        </div>
      </section>

      <div className="divider" />

      <section id="cities">
        <div className="sec-inner">
          <SecHead
            tag="Where we are" title="Live in one city." em="Verified in six."
            sub="Vizag is open today. The rest are in verification — rooms walked, kitchens tasted, in that order."
          />

          <div className="city-grid reveal">
            {CITY_CARDS.map((c, i) => (
              <div className="ccard" key={c.name} style={{ '--i': String(i) }}>
                <div className="cimg-wrap">
                  <img
                    className="cimg" src={c.src} alt={c.name} loading="lazy"
                    onError={e => {
                      // Remote hosts go away; fall back to the brand ground
                      // rather than leaving a broken-image glyph in the grid.
                      e.currentTarget.style.display = 'none';
                      e.currentTarget.parentElement.style.background = 'var(--forest)';
                    }}
                  />
                  <div className="cimg-overlay" />
                </div>
                <div className="ccard-body">
                  <div className="cname">{c.name}</div>
                  <div className={`cstat ${c.live ? 'cs-live' : 'cs-soon'}`}>
                    {c.live ? 'Live now' : 'In verification'}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
